name: Test Pimcore Skeleton

on:
  # Trigger the workflow on push or pull request, but only for the 10.x branch
  # See: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-using-multiple-events-with-activity-types-or-configuration
  push:
    branches:
    - "[0-9]+.x"
  pull_request:
    branches:
     - "[0-9]+.x"

jobs:
  test-pimcore-skeleton:
    runs-on: ubuntu-latest
    steps:
    # Check out the repo in a sub-dir to see if it can serve as
    # teplate for `composer create-project`
    # See: https://github.com/actions/checkout#usage
    - uses: actions/checkout@v2
      with:
        path: 'skeleton'

    - name: Pull latest pimcore 10.x image
      run: |
        # Echo commands and terminate on first error
        set -ex
        
        # Pull latest build of pimcore's image
        docker pull docker.io/pimcore/pimcore:PHP8.0-fpm

    - name: Create Project from Skeleton in pimcore 10.x environment
      run: |
        # Echo commands and terminate on first error
        set -ex
        
        # Try creating a new project with composer using contents of this repo as the package.
        # We execute composer within docker container to suttisfy platform requirements.
        # The value of ´"url":` must match checkout path in the first step.
        #
        # See: https://getcomposer.org/doc/03-cli.md#create-project
        # See: https://getcomposer.org/doc/05-repositories.md#path
        docker run \
          --volume=${{ github.workspace }}/:/test/ \
          --workdir=/test/ \
          --user=$(id -u):$(id -g) \
          docker.io/pimcore/pimcore:PHP8.0-fpm \
            composer create-project \
              pimcore/skeleton:@dev \
              --repository='{"type": "path", "url": "./skeleton"}' \
              sample-project

    - name: Smoke-test compose file
      run: |
        # Echo commands and terminate on first error
        set -ex
        
        # Check the compose file
        docker-compose -v
        cd sample-project/
        docker-compose config
